### PR TITLE
Sidebar

### PR DESCRIPTION
**Pull request by rgbkrk**
Continuing on with @philplckthun's work, bringing in some things from #20.

### CODE REVIEW

**Comment by rgbkrk** [comment]
About won't stay in, this is just a minimal view to test the nav.

screenshot 2015-12-11 12 04 21

**Comment by rgbkrk** [comment]
If I do the sidebar with `<ul>`s they end up like this:

screenshot 2015-12-11 12 07 34

**Comment by kitten** [comment]
@rgbkrk This is how it looks right now

Update

**Comment by rgbkrk** [comment]
Gorgeous. How's "About" look?

**Comment by rgbkrk** [comment]
screenshot 2015-12-11 18 57 21

**Comment by rgbkrk** [comment]
Every view is going to end up needing that color.

**Comment by luckydonald** [comment]
https://github.com/RobCoIndustries/pipboy/pull/24#issuecomment-164089928 Looking good.

**Comment by rgbkrk** [comment]
Cool. Let's go with it an iterate. We'll need to pass the styling on down to components I think. Today I'll be working on my fundamentals some more.

**Pull request merged**
