### PR TITLE
Borderless

### PR DESCRIPTION
**Pull request by luckydonald**
I don’t like the window borders.

This is some idea which occurred me.

### CODE REVIEW

**Comment by luckydonald** [comment]
hm it included d2db761, from #26.

**Comment by luckydonald** [comment]
It just looks so much better on the desktop.
bildschirmfoto 2015-12-13 um 06 38 56

bildschirmfoto 2015-12-13 um 06 01 05

Windows:
2015-12-13 18_33_04-greenshot

The sidebar is where to drag that window. 
If you wanna close it, you can still use the menu or hotkeys.

**Comment by rgbkrk** [comment]
That's much better, especially on Windows. I'm running the app on a Mac so I wasn't paying much attention to it.

Thanks again @luckydonald! I've also made you a member of RobCoIndustries. Welcome!

**Comment by rgbkrk** [comment]
Since I already merged the other PR, this will just bring the one commit in. You'll want to make sure to start new branches off master next time. No big deal though!

**Comment by luckydonald** [comment]
>  I've also made you a member of RobCoIndustries. Welcome!

Thank you

**Comment by luckydonald** [comment]
Strange, the [members page](https://github.com/orgs/RobCoIndustries/people) doesn't list me.

**Comment by rgbkrk** [comment]
You'll have to accept the invitation by visiting https://github.com/RobCoIndustries.

screenshot 2015-12-13 12 05 53

**Comment by luckydonald** [comment]
Oh, on top it was! I scrolled past it each and every time.
Funfact: I don't even know how to node.js.
I am more a python/django guy.
But 'eh. Here we go, lol.
(I am tempted to throw in the term 'YOLO'.)

**Comment by rgbkrk** [comment]
Thanks for maximize! This is nice - I'm back home and free to play+code now.

**Comment by rgbkrk** [comment]
Belated feedback (can become new issues or ignored :wink:):
- The fullscreen selection should change how it appears when activated vs. not
- While you and I know to drag the sidebar, I'm not sure if others are going to pick up on that right away. Any ideas about cues we can make about the app being grabbable by the sidebar?

**Comment by luckydonald** [comment]
About the second point I am actually concerned too.
I would like to imitate the OS's buttons 
screen shot 2015-12-14 at 09 56 16
just more simple, and in the fitting pip boy color.
Then you get a normal bar on top to drag.

**Comment by luckydonald** [comment]
Photoshop mockups:
Mac.
Mac Mockup - 729f8222-a166-11e5-9f0b-759ea06f146b kopie
Mac on Hover.
Mac Mockup, hover - 729f8222-a166-11e5-9f0b-759ea06f146b_2
Windows.
Windows Mockup - f2a6406c-a1c7-11e5-89df-de3fb0972249
**edit**: 
 I would probably make the mac buttons part of the navigation bar, so we don't loose map space.
On windows I can just lay the buttons over some small part in the top left corner of the map, so space is much more efficiently used there too.

**Comment by kitten** [comment]
@luckydonald and at this point I'm wondering if there's any worth left regarding a custom non-bordered window. Is it worth removing a system compliant feature which brings familiarity and intuitive behavior with it just so we don't have to care about that aspect design wise?

**Comment by luckydonald** [comment]
The default window borders waist much space, and also Windows adds more border on top and at all sides. 
Also, with this there will no menubar be rendered on windows.
moved here from #22

> 2015-12-11 00_24_17-pipboy
> Also the menu bar (Edit, View, Window, Help) isn't hidden in Fullscreen mode... (**edit**: See #27)

**Comment by luckydonald** [comment]
Draggable parts has to be set. See [electron: -webkit-app-region](https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#draggable-region)
So another solution is to mark basically the whole window draggable, and exclude parts with  `-webkit-app-region: no-drag`.
I was concerned that might later conflict with moving the map or something, as there the css has to be included every time.
A question of implicit vs explicit, turn it off vs turn it on.
(I was lazy so I chose to explicitly turn it on on only one element)

**Comment by kitten** [comment]
@luckydonald Fair enough. I think we might want to use a cursor for indicate that the window is draggable. Otherwise we just have to add `-webkit-app-region: no-drag` into the reset.css and that's it (?)

**Comment by luckydonald** [comment]
We have to either
- apply  `drag` to the root and exclude buttons and movable parts later with `no-drag`

or
- set only specific parts as `drag` and don't care about the rest (which defaults to `no-drag`) 

The first has the benefit that you can drag everywhere where no input is, but needs more careful selection what to parts to include (e.g. selectable text etc.)

The second makes it easier for us to maintain, but will result in less draggable parts.

cursor is good, probably `cursor: move`? [Cursor reference page](http://www.echoecho.com/csscursors.htm)
I am not sure what reset.css does, where it applies.

**Pull request merged**
