### PR TITLE
Introductory React Router.

### PR DESCRIPTION
**Pull request by rgbkrk**
Styling way off.

screenshot 2015-12-10 16 04 06

screenshot 2015-12-10 16 04 11

Wanted to start introducing routes even with a crappy nav bar.

Halp @philplckthun

### CODE REVIEW

**Comment by kitten** [comment]
https://www.youtube.com/watch?v=9OyDK98w77M

**Comment by rgbkrk** [comment]
Current layout (yes, styling is not adjusted):

screenshot 2015-12-10 17 35 43

**Comment by rgbkrk** [comment]
Seems like we should submit the color prop top down to the children of the main app.

**Comment by rgbkrk** [comment]
Closing in favor of #24

**Pull request closed without merging**
