### PR TITLE
Implement the beginnings of ServerSelection.

### PR DESCRIPTION
**Pull request by rgbkrk**
This is a humble beginning for ServerSelection. These were clickable, then I stashed that while trying to figure out how to get the data flow right.

### CODE REVIEW

**Comment by luckydonald** [comment]
Now it either stays complete black or does instantly connect.
Or is that a feature, connecting instantly if there is only one available?

**Comment by rgbkrk** [comment]
Hold off on this one, it's a Work in Progress [WIP]. I've got a commit in draft that should finish this series of transitions.

As for `WebkitAppRegion`, I noticed an error in the chrome dev console, switched it over and it was ok. I think for plain Electron apps `-webkit-app-region` is right whereas for React it wants the CamelCase. I should probably that into a separate PR.

**Comment by rgbkrk** [comment]
Alright @luckydonald, this is free to try out now! :wink:

Needs styling, just aimed for getting this working.

**Comment by rgbkrk** [comment]
It's kind of annoying that `Link`s in react router aren't relative, even though setting up the Route is. Ended up having to pass in a basepath. Of course, that's also an issue invented by me setting the path to be the IP of the server in use. Tried several approaches prior to pathing, wasn't sure what was going to work best.

**Comment by luckydonald** [comment]
I was thinking:
It would be great to already have the sidebar in this view, so we can include the fullscreen button, the about, and later a settings tab (#32) without an active connection.
Also we can get the draggable area back.

**Comment by luckydonald** [comment]
Okey, it found an ip, and I could click it. Afterwards there was page saying `woo`:smile: .
It still doesn't seem to refresh the list (on mac `cmd+R` is a workaround).

**Comment by luckydonald** [comment]
screen_shot_2015-12-17_at_14_28_06
Note: the python simulator died midway, maybe the cause?
`during processing of request from ('localhost', 49586)` (File "pipboy.py", line 559, in receive  `error: unpack requires a string argument of length 5`)

**Comment by rgbkrk** [comment]
Current look:

screenshot 2015-12-17 16 30 03

**Comment by rgbkrk** [comment]
One thing that's fairly different on connection here: I've now swapped it so the heartbeat is triggered after connect.

**Comment by luckydonald** [comment]
Works. Yay.

**Pull request merged**
